### ISSUE TITLE
Nums passed to foreign methods.

### ISSUE THREAD

**Issue by PureFox48** [CrazyInfin8/WrenGo#2]
One other thing I've just noticed is that Nums passed as arguments to Wren foreign methods are coming across to Go as float32's rather than float64's which is losing accuracy.

This seems to be as a result of this function in vm.go:

```go
func (vm *VM) getSlotValue(slot int) (value interface{}) {
	cSlot := C.int(slot)
	switch C.wrenGetSlotType(vm.vm, C.int(cSlot)) {
	//...
	case C.WREN_TYPE_NUM:
		return float32(C.wrenGetSlotDouble(vm.vm, cSlot))
	//...
	}
}
```
I don't understand why this is necessary when Nums are essentially float64's and slots can handle doubles just fine.

**Comment by CrazyInfin8** [comment]
Fixed. 
I guess I didn't know whether Nums were 64-bit or 32-bit
