### ISSUE TITLE
ListHandle's Insert and InsertAt methods undocumented.

### ISSUE THREAD

**Issue by PureFox48** [CrazyInfin8/WrenGo#3]
Perhaps you could add these to the documentation when you have time.

**Comment by CrazyInfin8** [comment]
Updated [go docs](https://pkg.go.dev/github.com/crazyinfin8/WrenGo) to show the latest documentations. Now it shows information for [Insert](https://pkg.go.dev/github.com/crazyinfin8/WrenGo#ListHandle.Insert) and [InsertAt](https://pkg.go.dev/github.com/crazyinfin8/WrenGo#ListHandle.InsertAt)
